version: "3.0"
services: 
  jdk:
    # build: .
    image: registry.cn-hangzhou.aliyuncs.com/fengxiu/alijdk
    ports: 
      - "8091:8091"
    volumes: 
      - "./build.sh:/root/work/build.sh"
    # 挂卷格式 "外面目录指定文件 ：/root/work/外面目录指定文件"
      # - "./jar/SpringBootWebFlux-1.0-SNAPSHOT.jar:/root/work/test.jar"
      - "../alijdk-test/:/root/work/alijdk-test"
    # 运行jar 使用下面这个
    # command: [
    #   java,
    #   -jar,
    #   test.jar
    # ]
    # 运行maven使用下面这个
    command: [
      sh,
      /root/work/build.sh
    ]
  oracle-jdk:
    image: registry.cn-hangzhou.aliyuncs.com/fengxiu/ojdk
    ports: 
      - "8091:8091"
    volumes: 
      - "./build.sh:/root/work/build.sh"
      - "./jar/:/root/work/"
      - "../alijdk-test/:/root/work/alijdk-test"
    command: [
      sh,
      /root/work/build.sh
    ]
  namesrv:
    image: rocketmqinc/rocketmq:4.3.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/namesrv/logs:/home/rocketmq/logs
      - ./data/namesrv/store:/home/rocketmq/store
    command: sh mqnamesrv
    broker:
      image: rocketmqinc/rocketmq:4.3.0
      container_name: rmqbroker
      ports:
        - 10909:10909
        - 10911:10911
      volumes:
        - ./data/broker/logs:/home/cz/logs
        - ./data/broker/store:/home/cz/store
        - ./data/broker/conf/broker.conf:/home/cz/workspace/bainianali/docker/data
      #command: sh mqbroker -n namesrv:9876
      command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf autoCreateTopicEnable=true
      depends_on:
        - namesrv